apiVersion: v1
kind: Secret
metadata:
  name: docker-hub-secret
  namespace: tekton-pipelines-secure
  annotations:
    tekton.dev/docker-0: https://index.docker.io/v1/
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "username": "skhussain786",
          "password": "Hussain@92",
          "email": "skiftekhar92@gmail.com"
        }
      }
    }

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
  namespace: tekton-pipelines-secure
secrets:
  - name: docker-hub-secret
imagePullSecrets:
  - name: docker-hub-secret
