apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: tekton-pipelines-secure
  annotations:
    tekton.dev/docker-0: https://index.docker.io/v1/
type: kubernetes.io/basic-auth
stringData:
  username: <docker_base64_encoded_username>
  password: <docker_base64_encoded_password>

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
  namespace: tekton-pipelines-secure
secrets:
  - name: regcred
